permit persist  k
permit nopass k as root  cmd /usr/bin/ntfs-3g
permit nopass k as root  cmd /usr/bin/umount
permit nopass k as root cmd /usr/bin/apt args update 
permit nopass k as root cmd /usr/bin/apt args upgrade
