#!/bin/sh
set -e
bwrap --unshare-all --share-net --die-with-parent --new-session \
--hostname localhost \
--clearenv \
--setenv HOME "$HOME" \
--setenv GTK_THEME Adwaita:dark \
--setenv MOZ_ENABLE_WAYLAND 1 \
--setenv WAYLAND_DISPLAY "$WAYLAND_DISPLAY" \
--setenv XDG_RUNTIME_DIR "$XDG_RUNTIME_DIR" \
--setenv PATH /usr/bin \
--setenv TZ "UTC" \
--dev /dev \
--proc /proc \
--tmpfs /tmp \
--dev-bind /dev/dri /dev/dri \
--dev-bind /dev/snd /dev/snd \
--ro-bind /sys/devices/pci0000:00 /sys/devices/pci0000:00 \
--symlink usr/lib /lib \
--symlink usr/lib64 /lib64 \
--ro-bind /usr/lib /usr/lib \
--ro-bind /usr/lib64 /usr/lib64 \
--ro-bind /sys/dev/char /sys/dev/char \
--ro-bind-try "$XDG_RUNTIME_DIR/pulse" "$XDG_RUNTIME_DIR/pulse" \
--ro-bind "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY" "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY" \
--ro-bind-try "$XDG_RUNTIME_DIR/bus" "$XDG_RUNTIME_DIR/bus" \
--ro-bind /usr/share /usr/share \
--ro-bind /etc/group /etc/group \
--ro-bind /etc/passwd /etc/passwd \
--ro-bind /etc/fonts /etc/fonts \
--ro-bind /etc/resolv.conf /etc/resolv.conf \
--ro-bind-try /etc/ssl /etc/ssl \
--ro-bind-try /etc/ca-certificates /etc/ca-certificates \
--bind-try /etc/resolv.conf /etc/resolv.conf \
--bind-try ~/.mozilla ~/.mozilla \
--bind-try ~/Downloads ~/Downloads \
--bind-try ~/mnt ~/mnt \
--bind ~/opt/firefox ~/opt/firefox \
--ro-bind-try ~/.local/share/fonts/ ~/.local/share/fonts/ \
~/opt/firefox/firefox "$@"
