#!/bin/sh
##get emoji from https://raw.githubusercontent.com/Mange/rofi-emoji/master/all_emojis.txt

chosen=$(cut -f 1,3,4,5  ~/.config/all_emojis.txt |wofi --dmenu -i -p 'emoji:' | cut -f1 )
[ -z "$chosen" ] && exit
if [ -n "$1" ]; then
    wtype "$chosen"
else
    printf "$chosen" | wl-copy
fi
