#!/bin/bash

function list_geometry () {
    [ "$2" = with_description ] && local append="\t\(.name)" || local append=
    swaymsg -t get_tree | jq -r '.. | (.nodes? // empty)[] | select(.'$1' and .pid) | "\(.rect.x),\(.rect.y) \(.rect.width)x\(.rect.height)'$append'"'
}

WINDOWS=`list_geometry visible with_description`
FOCUSED=`list_geometry focused`

CHOICE=`wofi --dmenu -p 'Screenshot' << EOF
fullscreen
region
focused
$WINDOWS
EOF`


op_on=`wofi --dmenu -p 'output to file:'  << EOF
no
yes
EOF`
case $op_on in
	yes) SAVEDIR=~/shot ;;
	no) SAVEDIR=/tmp  ;;
    esac


mkdir -p -- "$SAVEDIR"
FILENAME="$SAVEDIR/$(date +'%Y-%m-%d-%H%M%S_screenshot.png')"



case $CHOICE in
    fullscreen)
        grim "$FILENAME"
    ;;
    region)
        grim -g "$(slurp)" "$FILENAME"
    ;;
    focused)
        grim -g "$FOCUSED" "$FILENAME"
    ;;
    '')
#        notify-send "Screenshot" "Cancelled"
        exit 0
        ;;
    *)
        GEOMETRY="`echo \"$CHOICE\" | cut -d$'\t' -f1`"
        grim -g "$GEOMETRY" "$FILENAME"
esac

# If swappy is installed, prompt the user to edit the captured screenshot
if command -v swappy $>/dev/null
then
    EDIT_CHOICE=`wofi --dmenu -p 'Edit'  << EOF
no
yes
EOF`

    case $EDIT_CHOICE in
        yes)
            swappy -f "$FILENAME" -o "$FILENAME"
            ;;
        no)
            ;;
        '')
            ;;
    esac
fi



wl-copy < "$FILENAME"
#notify-send "Screenshot" "File saved as <i>'$FILENAME'</i> and copied to the clipboard." -i "$FILENAME"

