#!/bin/bash

# Check if yt-dlp is installed
if ! command -v yt-dlp &> /dev/null; then
    echo "yt-dlp could not be found, please install it first."
    exit 1
fi
# change it to $1 for script 
DL_FILE="/tmp/dl"

# Infinite loop for downloading videos
while true; do

URL=$(head -n 1 "$DL_FILE") || exit 1  # Get the first URL
if [ -n "$URL" ]; then
    [ -z "$URL" ] && continue  # Skip empty lines
    echo "Downloading video..."
    yt-dlp --cookies-from-browser firefox -f bestaudio+bestvideo  "$URL"
    if [ $? -eq 0 ]; then
        echo "Download completed successfully!"
        sed -i '1d' "$DL_FILE"
    else
        echo "There was an error during the download or merge process."
    fi

fi
done
