#!/bin/sh

case $BLOCK_BUTTON in
	6) foot nano "$0" ;;
esac

battery='/sys/class/power_supply/BAT0'
capacity="$(cat "$battery/capacity" 2>&1)"
    
case "$(cat "$battery/status" 2>&1)" in
        "Full") status="" ;;
        "Discharging") status="d" ;;
        "Charging") status="" ;;
        "Not charging") status="🛑" ;;
        "Unknown") status="♻️" ;;
        *) exit 1 ;;
esac
    
if [ "$capacity" -gt "95" ] && [ "$status" = "d" ] ; then  status=" "
elif [ "$capacity" -gt "75" ] && [ "$status" = "d" ]; then status=" "
elif [ "$capacity" -gt "50" ] && [ "$status" = "d" ]; then status=" "
elif [ "$capacity" -gt "25" ] && [ "$status" = "d" ] ; then status=" "
elif [ "$capacity" -lt "25" ] && [ "$status" = "d" ] ; then  status=" " && warn="❗"  
fi

    
# Prints the info
printf "%s%s%d%%" "$status "  "$warn" "$capacity" ; unset warn
printf "\\n"

 
