#!/bin/sh

case $BLOCK_BUTTON in
	6) foot nano "$0" ;;
esac

battery='/sys/class/power_supply/BAT0'
capacity="$(cat "$battery/capacity" 2>&1)"
status="$(head -c 1 "$battery/status" 2>&1)"

printf "%s%d%%" "$status "  "$capacity"
printf "\\n"
