#!/bin/sh
case $BLOCK_BUTTON in
	4) brightnessctl s 1%+ >> /dev/null;;
	5) brightnessctl s 1%- >> /dev/null;;
	6) foot nano "$0" ;;
	esac
BNESS="$(brightnessctl get)"
MAX="$(brightnessctl max)"
PERC="$((BNESS*100/MAX))"
BLIGHT=${PERC%.*}
ICON=""	

echo $ICON $BLIGHT
