#!/bin/sh
case $BLOCK_BUTTON in
	1) swaymsg  "input 1:1:AT_Translated_Set_2_keyboard xkb_switch_layout next" >> /dev/null ;;
        6) foot nano "$0" ;;
         esac
KBLAYOUT=$(swaymsg -t get_inputs -r | jq -r '.[] | select(.identifier == "1:1:AT_Translated_Set_2_keyboard") | .xkb_active_layout_name')
echo $KBLAYOUT 
