#!/bin/sh
case $BLOCK_BUTTON in
        1) foot -e alsamixer  ;;
         2) amixer sset Master toggle  >>/dev/null ;;
         4) amixer sset Master 5%+ >>/dev/null ;;
         5) amixer sset Master 5%- >>/dev/null ;;
         6) foot -e "$EDITOR" "$0" ;;
 esac

volstat="$(amixer get Master)"
vol=$(echo "$volstat" | grep -o "\[[0-9]\+%\]" | sed "s/[^0-9]*//g;1q")
echo "$volstat" | grep "\[off\]" >/dev/null && printf "off\\n" 

icon=""

echo "$icon $vol"
